---
- hosts: webserver
  become: yes
  vars_files:
    - vars.yml

  tasks:
    - name: Purge dotnet-sdk-7.0
      apt:
        name: dotnet-sdk-7.0
        state: absent

    - name: Remove Microsoft package repository and update
      block:
        - name: Remove microsoft-prod.list
          file:
            path: /etc/apt/sources.list.d/microsoft-prod.list
            state: absent
        - name: Update apt cache
          apt:
            update_cache: yes

    - name: Install dotnet7
      apt:
        name: dotnet7
        state: present

    - name: Check dotnet info
      command: dotnet --info
      register: dotnet_info
      changed_when: false

    - debug: 
        var: dotnet_info.stdout_lines
    - name: Install required packages
      apt:
        name:
          - nginx
          - certbot
          - python3-certbot-nginx
          - git
          - apt-transport-https
          - wget
          - snapd
        state: present

    - name: Copy nginx configuration
      template:
        src: nginx.default.conf.j2
        dest: /etc/nginx/sites-enabled/default
      notify:
        - Restart nginx

    - name: Install Certbot and Nginx plugin
      apt:
        name:
          - certbot
          - python3-certbot-nginx
        state: present

    - name: Check if SSL certificate exists
      stat:
        path: /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem
      register: cert_stat
    
    - name: Obtain a certificate using the Nginx plugin
      command:
        cmd: certbot --nginx -d {{ domain_name }} -d {{ domain_alias }} --non-interactive --agree-tos --email {{ admin_email }}
        creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
      when: not cert_stat.stat.exists
      notify:
        - Restart nginx

    - name: Copy nginx configuration
      template:
        src: nginx.ssl.conf.j2
        dest: /etc/nginx/sites-enabled/default
      notify:
        - Restart nginx

    - name: Set up certbot renewal cron job
      cron:
        name: Certbot Renewal
        minute: "30"
        hour: "2"
        job: "certbot renew --quiet --post-hook 'systemctl reload nginx'"

    - name: Clone project repository
      git:
        repo: "{{ git_repository }}"
        dest: "{{ project_directory }}"
        version: main

    - name: Restore and build the project
      command:
        cmd: dotnet build --configuration Release
        chdir: "{{ project_directory }}"

    - name: Kill all tmux sessions
      shell: tmux list-sessions -F '#S' | xargs -r tmux kill-session -t
      ignore_errors: yes

    - name: Start app in tmux
      shell: |
        tmux new-session -d -s mysession
        tmux send-keys -t mysession 'dotnet run --configuration Release --urls:localhost:5000' C-m
      args:
        chdir: "{{ project_directory }}"

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
