---
- hosts: webserver
  become: yes
  vars_files:
    - vars.yml
  tasks:
    - name: Create a new user
      user:
        name: dev
        state: present

    - name: Set authorized key taken from file
      authorized_key:
        user: dev
        state: present
        key: "{{ lookup('file', 'S:/SSH/ssh-dev.pub') }}"
